<?php
function my_crud_menu()
{
    $item['my_crud']=array('title'=>'List Records','description'=>'','route'=>'my_crud.mycrud_controller_listing');

    $item['my_crud/form/data']=array('title'=>'ADD / Edit Form','description'=>'','route'=>'my_crud.mycrud_form');

    $item['my_crud/form/delete/{cid}']=array('title'=>'Delete Records','description'=>'','route'=>'my_crud.delete_form');

return $item;
}

?>